server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ai_healing_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      bindings:
        incident-in-0:
          destination: incident-events
          group: incident-manager-group

